schema = {
     "spotify" : [
        {"name": "first_name", "type": "STRING", "mode": "NULLABLE"},
        {"name": "last_name", "type": "STRING", "mode": "NULLABLE"},
        {"name": "gender", "type": "STRING", "mode": "NULLABLE"},
        {"name": "city", "type": "STRING", "mode": "NULLABLE"},
        {"name": "state", "type": "STRING", "mode": "NULLABLE"},
        {"name": "country", "type": "STRING", "mode": "NULLABLE"},
        {"name": "latitude", "type": "FLOAT", "mode": "NULLABLE"},
        {"name": "longitude", "type": "FLOAT", "mode": "NULLABLE"},
        {"name": "listen_timestamp", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "song_id", "type": "STRING", "mode": "NULLABLE"},
        {"name": "artist_name", "type": "STRING", "mode": "NULLABLE"},
        {"name": "artist_id", "type": "STRING", "mode": "NULLABLE"},
        {"name": "song_title", "type": "STRING", "mode": "NULLABLE"},
        {"name": "album_name", "type": "STRING", "mode": "NULLABLE"},
        {"name": "release_date", "type": "STRING", "mode": "NULLABLE"},
        {"name": "duration_ms", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "danceability", "type": "FLOAT", "mode": "NULLABLE"},
        {"name": "energy", "type": "FLOAT", "mode": "NULLABLE"},
        {"name": "key", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "loudness", "type": "FLOAT", "mode": "NULLABLE"},
        {"name": "mode", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "speechiness", "type": "FLOAT", "mode": "NULLABLE"},
        {"name": "acousticness", "type": "FLOAT", "mode": "NULLABLE"},
        {"name": "instrumentalness", "type": "FLOAT", "mode": "NULLABLE"},
        {"name": "liveness", "type": "FLOAT", "mode": "NULLABLE"},
        {"name": "valence", "type": "FLOAT", "mode": "NULLABLE"},
        {"name": "tempo", "type": "FLOAT", "mode": "NULLABLE"},
        {"name": "year", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "month", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "hour", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "day", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "duration_minutes", "type": "FLOAT", "mode": "NULLABLE"},
        {"name": "full_name", "type": "STRING", "mode": "NULLABLE"}
    ]
}